name: CI
on:
  push:
    branches: [main, lmm/aarch64]
    tags-ignore: [dev]
  pull_request:
    branches: [main]
defaults:
  run:
    shell: bash

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Check Code style quickly by running `rustfmt` over all code
  dist_linux_aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update --no-self-update stable && rustup default stable
      - run: rustup target add aarch64-unknown-linux-gnu
      - run: sudo apt update -y && sudo apt install gcc-aarch64-linux-gnu pkg-config-aarch64-linux-gnu  -y
      - run: |
          cargo build --manifest-path crates/cli/Cargo.toml --target aarch64-unknown-linux-gnu --features vendored-openssl --release
